### PR TITLE
Locally set comment-start

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by david-christiansen** [comment]
Unfortunately, it's a bit of a pain to get syntactic fontification for JonPRL comments, because the syntax table is set up for only two-character delimiters. You'll have to use `syntax-propertize-function` (or I'll have to).

**Comment by jonsterling** [comment]
I have no opinion about what comments should look like, so if we want to
change them to any symbol that is easier to deal with, then let's do so!

**Comment by david-christiansen** [comment]
This is really a case of Emacs being a bit crappy, and assuming that every
language is either Lisp or C. If you want it to change the language to
account for Emacs being dumb, then I'd just steal C's syntax. But getting
the syntax info right is also doable with some buffer-scanning in Emacs.

One thing I've really liked in Python, Lisp and Idris is having a
distinction between documentation and comments, where the documentation for
a name is accessible using the language tools and the comments exist as,
well, comments. But now we're really getting into Wadler's Law territory...

2015-06-13 20:39 GMT+02:00 Jonathan Sterling notifications@github.com:

**Comment by cpitclaudel** [comment]
You could also weight in on this question: http://emacs.stackexchange.com/questions/12126/three-characters-comment-syntax

**Comment by david-christiansen** [comment]
Done.

**Comment by david-christiansen** [comment]
OK, I just added syntax scanning for comments. Let me know if it does what you want, @freebroccolo  and @jonsterling.

**Pull request merged**
